language: shell

services:
  - docker

before_install:
  - IMGNAME=raplaeditor2:$(date +"%Y%m%d%H%M%S")
  - echo "${IMGNAME}"
  - docker build -t ${IMGNAME} .
  - docker run -d --privileged --name raplaEditorTest ${IMGNAME}
  - docker ps -a

script:
  - sleep 60
  - export CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' raplaEditorTest)
  - echo "Container IP Address: ${CONTAINER_IP}"
  - status_code=$(curl -s -o /dev/null -w "%{http_code}" http://${CONTAINER_IP}:9014/TINF22B2)
  - echo "HTTP Status Code: ${status_code}"
  - if [ $status_code -eq 200 ]; then echo "Request successful"; else echo "Request failed"; exit 1; fi

after_success:
  - echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker images
  - docker tag ${IMGNAME} ${DOCKER_USERNAME}/${IMGNAME}
  - docker push ${DOCKER_USERNAME}/${IMGNAME}