language: minimal

services:
  - docker

before_install:
  - docker build -t raplaeditor2 .

script:
  - docker run -d -p 9014:9014 my_image
  - sleep 5 # Give the container some time to start
  - status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9014/TINF22B2)
  - echo "HTTP Status Code: $status_code"
  - if [ $status_code -eq 200 ]; then echo "Request successful"; else echo "Request failed"; exit 1; fi

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag my_image "$DOCKER_USERNAME/my_image"
  - docker push "$DOCKER_USERNAME/my_image"
